### PR TITLE
Minor changes to permission names.

### PR DESCRIPTION
**Pull request by laxderek**
[#134825137]

### CODE REVIEW

**Comment by laxderek** [comment]
Self reviewing because its a small naming change.

**Comment by pcsouza** [comment]
@laxderek Please don't self-review a breaking change to HOLMS.Platform.

Enum naming changes break everything. Instead of bundling them into whatever you're working on, make them their own PR so that they can get pushed through independently and keep everyone unblocked.

**Comment by laxderek** [comment]
@pcsouza I chose to do so in this case due to the breaking change related
to the removal qualifications that had been outstanding for a while. I have
had the PR ready to fix this waiting for a few days now. Is this
qualification change fixed?

**Comment by pcsouza** [comment]
@laxderek The qualification change has been fixed, and your PR with the fix for this issue is approved, but has a merge conflict.

**Pull request merged**
